### ISSUE TITLE
 Failed to connect to ovsdb

### ISSUE THREAD

**Issue by caoxiaojian** [liucimin/port-exporter#7]
[root@zipkin-001 bin 14:39:54]# ./port_exporter -h
ERROR: logging before flag.Parse: F1114 14:39:58.401225   31960 ovsdb_tools.go:28] Failed to connect to ovsdb
goroutine 1 [running, locked to thread]:
github.com/port-exporter/vendor/github.com/golang/glog.stacks(0xc0000a4000, 0xc000348000, 0x4c, 0x9a)
        /root/go/src/github.com/port-exporter/vendor/github.com/golang/glog/glog.go:769 +0xb8
github.com/port-exporter/vendor/github.com/golang/glog.(*loggingT).output(0xe15ba0, 0xc000000003, 0xc00011eb60, 0xdc1344, 0xe, 0x1c, 0x0)
        /root/go/src/github.com/port-exporter/vendor/github.com/golang/glog/glog.go:720 +0x372
github.com/port-exporter/vendor/github.com/golang/glog.(*loggingT).printDepth(0xe15ba0, 0x3, 0x1, 0xc0001efe38, 0x1, 0x1)
        /root/go/src/github.com/port-exporter/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/port-exporter/vendor/github.com/golang/glog.(*loggingT).print(...)
        /root/go/src/github.com/port-exporter/vendor/github.com/golang/glog/glog.go:637
github.com/port-exporter/vendor/github.com/golang/glog.Fatal(...)
        /root/go/src/github.com/port-exporter/vendor/github.com/golang/glog/glog.go:1128
github.com/port-exporter/pkg/tools.NewOvsdbHandler(0x644e68bfd7f99d8c)
        /root/go/src/github.com/port-exporter/pkg/tools/ovsdb_tools.go:28 +0x32b
github.com/port-exporter/collector.NewOvsdbInterfaceCollector(0x922f40, 0xc000277020)
        /root/go/src/github.com/port-exporter/collector/ovs_ports.go:42 +0x26
github.com/port-exporter/collector.init.1()
        /root/go/src/github.com/port-exporter/collector/ovs_ports.go:12 +0x26

**Comment by liucimin** [comment]
Sorry i have just see the isssue.

in my code the ovs client connect the ovsdb use "localhost:6640"

```
	// connect to OVS
	ovs, err := libovsdb.Connect("localhost", 6640)
	if err != nil {
		glog.Fatal("Failed to connect to ovsdb")
	}
```

So you should start your ovs with the 6640 port in the same network namespace.
